name: Build

on:
  push:
  pull_request:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build-macos:
    name: Build macOS
    runs-on: macos-11
        
    env:
      JOB_TYPE: BUILD
    steps:
      - uses: actions/checkout@v2
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 13.1

      - name: Compile Debug
        run: xcodebuild -target "USBPatcher (macOS)" -configuration Debug

      - name: Compile Release
        run: xcodebuild -target "USBPatcher (macOS)" -configuration Release
